{% set name = "rustworkx" %}
{% set version = "0.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: ef3c6fb3bd7e6a18919023330f3961702346d8afbe95aa5f446f9b222ee72391

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - numpy >=1.16.0,<3
    - python
  run_constrained:
    - matplotlib >=3.0
    - matplotlib-base >=3.0
    - pillow >=5.4

test:
  imports:
    - rustworkx
    - rustworkx.visualization
  commands:
    - pip check
    - stestr --test-path=tests run  # [build_platform == target_platform]
  requires:
    - fixtures  # [build_platform == target_platform]
    - networkx >=2.5  # [build_platform == target_platform]
    - pip
    - stestr >=4.1  # [build_platform == target_platform]
    - testtools >=2.5.0  # [build_platform == target_platform]
  source_files:
    - tests/*

about:
  home: https://github.com/Qiskit/rustworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - IvanIsCoding
    - BastianZim
    - wshanks
