{% set name = "rustworkx" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: d630e3dd2984bb3dfa1cc9af5d960c3b970a5c0512551d8340996e9e61e2ca44

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - numpy >=1.16.0,<2
    - python
  run_constrained:
    - matplotlib >=3.0
    - pillow >=5.4

test:
  imports:
    - rustworkx
    - rustworkx.visualization
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/rustworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
