context:
  name: rustworkx
  python_name: rustworkx
  version: "0.17.1"
  python_min: "3.9"

package:
  name: rustworkx
  version: ${{ version }}

source:
  url: https://github.com/Qiskit/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: dc248da9cc364b81ac67f5d67b626ee3f03a1f6299f7a9b4d0a0501548715365

build:
  number: 2
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv
  skip: not (match(python, python_min ~ ".*") and is_abi3)
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
      - python
      - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - pip
    - setuptools >=77.0.0
    - setuptools-rust >=1.9
  run:
    - numpy >=1.16.0,<3
    - python
  run_constraints:
    - matplotlib >=3.0
    - matplotlib-base >=3.0
    - pillow >=5.4

tests:
  - python:
      imports:
        - rustworkx
        - rustworkx.visualization
      python_version: ["${{ python_min ~ '.*' }}"]  
  - script:
      - pip check
      - if: build_platform == target_platform
        then:
          - python -m unittest discover tests
    requirements:
      run:
        - if: build_platform == target_platform
          then:
            - networkx >=2.5
        - pip
    files:
      source:
        - tests/*

about:
  homepage: https://www.rustworkx.org/
  repository: https://github.com/Qiskit/rustworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - IvanIsCoding
    - BastianZim
    - wshanks
