context:
  name: rustworkx
  python_name: rustworkx
  version: "0.18.0"

package:
  name: rustworkx
  version: ${{ version }}

source:
  url: https://github.com/Qiskit/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: c0a47afd9a16f560d46a3f95b11a9606c8da958b6a9e9ec4e69e0063801342b2

build:
  number: 3
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv
  skip: not (match(python, python_min ~ ".*") and is_abi3)
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - pip
    - setuptools >=77.0.0
    - setuptools-rust >=1.9
  run:
    - numpy >=1.16.0,<3
    - python
  run_constraints:
    - matplotlib >=3.0
    - matplotlib-base >=3.0
    - pillow >=5.4

tests:
  - python:
      imports:
        - rustworkx
        - rustworkx.visualization
      python_version: ["${{ python_min ~ '.*' }}"]
  - script:
      - pip check
      - if: build_platform == target_platform
        then:
          - python -m unittest discover tests
    requirements:
      run:
        - if: build_platform == target_platform
          then:
            - networkx >=2.5
        - pip
    files:
      source:
        - tests/*

about:
  homepage: https://www.rustworkx.org/
  repository: https://github.com/Qiskit/rustworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - IvanIsCoding
    - BastianZim
    - wshanks
